/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/robot.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.33, 0]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Mat1} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Mat2} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Mat3} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials.Mat4} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0, 1.33, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[0, 1.33, 0.03]} />
    </group>
  )
}

useGLTF.preload('/robot.glb')
